#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_APP_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${POSTGRES_APP_USER}', '${POSTGRES_APP_PASSWORD}');
  END IF;
END
\$\$;

SELECT format('CREATE DATABASE %I OWNER %I', '${POSTGRES_APP_DB}', '${POSTGRES_APP_USER}')
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POSTGRES_APP_DB}')
\gexec
EOSQL
