{
 "title": "API Overview",
 "tags": [
  "api",
  "fintech"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(api_http_request_duration_seconds_bucket[5m])) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(api_http_request_duration_seconds_bucket[5m])) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(api_http_request_duration_seconds_bucket[5m])) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(api_http_requests_total[5m])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(api_http_requests_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rate Limiter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(api_ratelimit_requests_total{result=\"allowed\"}[5m])",
     "legendFormat": "Allowed"
    },
    {
     "expr": "rate(api_ratelimit_requests_total{result=\"rejected\"}[5m])",
     "legendFormat": "Rejected (429)"
    }
   ]
  },
  {
   "title": "Token Bucket Refills",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_ratelimit_bucket_refills_total"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_http_requests_in_flight)"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_http_requests_total{status=~\"5..\"}[5m])) / sum(rate(api_http_requests_total[5m])) * 100"
    }
   ]
  }
 ]
}