// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type IdempotencyKey struct {
	Key         string    `json:"key"`
	RequestHash string    `json:"request_hash"`
	PayoutID    uuid.UUID `json:"payout_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Payout struct {
	ID                 uuid.UUID `json:"id"`
	State              string    `json:"state"`
	AmountCents        int64     `json:"amount_cents"`
	Currency           string    `json:"currency"`
	Rail               string    `json:"rail"`
	Provider           *string   `json:"provider"`
	ExternalID         *string   `json:"external_id"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	GlobalRetryCount   int32     `json:"global_retry_count"`
	ProviderRetryCount int32     `json:"provider_retry_count"`
}
