// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const cancelPayoutIfCancelable = `-- name: CancelPayoutIfCancelable :one
UPDATE payouts
SET state = 'canceled', updated_at = now()
WHERE id = $1
  AND state = ANY($2::text[])
RETURNING id, state, amount_cents, currency, rail, provider, external_id, created_at, updated_at
`

type CancelPayoutIfCancelableParams struct {
	ID               uuid.UUID `json:"id"`
	CancelableStates []string  `json:"cancelable_states"`
}

// Atomically transitions a payout to canceled only if it is in a cancelable state.
// Returns the updated row; pgx.ErrNoRows if not found or state not cancelable.
func (q *Queries) CancelPayoutIfCancelable(ctx context.Context, arg CancelPayoutIfCancelableParams) (Payout, error) {
	row := q.db.QueryRow(ctx, cancelPayoutIfCancelable, arg.ID, arg.CancelableStates)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.AmountCents,
		&i.Currency,
		&i.Rail,
		&i.Provider,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (state, amount_cents, currency, rail, provider, external_id)
VALUES ($1, $2, $3, $4, $5::text, $6)
RETURNING id, state, amount_cents, currency, rail, provider, external_id, created_at, updated_at
`

type CreatePayoutParams struct {
	State       string  `json:"state"`
	AmountCents int64   `json:"amount_cents"`
	Currency    string  `json:"currency"`
	Rail        string  `json:"rail"`
	Provider    *string `json:"provider"`
	ExternalID  *string `json:"external_id"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.State,
		arg.AmountCents,
		arg.Currency,
		arg.Rail,
		arg.Provider,
		arg.ExternalID,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.AmountCents,
		&i.Currency,
		&i.Rail,
		&i.Provider,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPayoutByExternalID = `-- name: FindPayoutByExternalID :one
SELECT id, state, amount_cents, currency, rail, provider, external_id, created_at, updated_at FROM payouts WHERE external_id = $1
`

func (q *Queries) FindPayoutByExternalID(ctx context.Context, externalID *string) (Payout, error) {
	row := q.db.QueryRow(ctx, findPayoutByExternalID, externalID)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.AmountCents,
		&i.Currency,
		&i.Rail,
		&i.Provider,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, payout_id, created_at FROM idempotency_keys WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.PayoutID,
		&i.CreatedAt,
	)
	return i, err
}

const getPayout = `-- name: GetPayout :one
SELECT id, state, amount_cents, currency, rail, provider, external_id, created_at, updated_at FROM payouts WHERE id = $1
`

func (q *Queries) GetPayout(ctx context.Context, id uuid.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayout, id)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.AmountCents,
		&i.Currency,
		&i.Rail,
		&i.Provider,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tryInsertIdempotencyKey = `-- name: TryInsertIdempotencyKey :one
INSERT INTO idempotency_keys (key, request_hash, payout_id)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO NOTHING
RETURNING key, request_hash, payout_id, created_at
`

type TryInsertIdempotencyKeyParams struct {
	Key         string    `json:"key"`
	RequestHash string    `json:"request_hash"`
	PayoutID    uuid.UUID `json:"payout_id"`
}

func (q *Queries) TryInsertIdempotencyKey(ctx context.Context, arg TryInsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, tryInsertIdempotencyKey, arg.Key, arg.RequestHash, arg.PayoutID)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.PayoutID,
		&i.CreatedAt,
	)
	return i, err
}

const updatePayoutState = `-- name: UpdatePayoutState :one
UPDATE payouts
SET state = $1, external_id = $2, provider = $3::text, updated_at = now()
WHERE id = $4
RETURNING id, state, amount_cents, currency, rail, provider, external_id, created_at, updated_at
`

type UpdatePayoutStateParams struct {
	State      string    `json:"state"`
	ExternalID *string   `json:"external_id"`
	Provider   *string   `json:"provider"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePayoutState(ctx context.Context, arg UpdatePayoutStateParams) (Payout, error) {
	row := q.db.QueryRow(ctx, updatePayoutState,
		arg.State,
		arg.ExternalID,
		arg.Provider,
		arg.ID,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.AmountCents,
		&i.Currency,
		&i.Rail,
		&i.Provider,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
