// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Atomically transitions a payout to canceled only if it is in a cancelable state.
	// Returns the updated row; pgx.ErrNoRows if not found or state not cancelable.
	CancelPayoutIfCancelable(ctx context.Context, arg CancelPayoutIfCancelableParams) (Payout, error)
	CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error)
	FindPayoutByExternalID(ctx context.Context, externalID *string) (Payout, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetPayout(ctx context.Context, id uuid.UUID) (Payout, error)
	TryInsertIdempotencyKey(ctx context.Context, arg TryInsertIdempotencyKeyParams) (IdempotencyKey, error)
	// Updates payout state and increments retry counters for retry processing.
	UpdatePayoutRetryState(ctx context.Context, arg UpdatePayoutRetryStateParams) (Payout, error)
	UpdatePayoutState(ctx context.Context, arg UpdatePayoutStateParams) (Payout, error)
}

var _ Querier = (*Queries)(nil)
