// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orchestrator/v1/orchestrator.proto

package orchestratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"` // idempotency key supplied by caller
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                    // minor units (e.g. cents)
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                 // ISO-4217 code
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`                 // routing hint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayoutRequest) Reset() {
	*x = CreatePayoutRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayoutRequest) ProtoMessage() {}

func (x *CreatePayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayoutRequest.ProtoReflect.Descriptor instead.
func (*CreatePayoutRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePayoutRequest) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

func (x *CreatePayoutRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePayoutRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePayoutRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type CreatePayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g. "PENDING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayoutResponse) Reset() {
	*x = CreatePayoutResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayoutResponse) ProtoMessage() {}

func (x *CreatePayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayoutResponse.ProtoReflect.Descriptor instead.
func (*CreatePayoutResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePayoutResponse) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

func (x *CreatePayoutResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutRequest) Reset() {
	*x = GetPayoutRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutRequest) ProtoMessage() {}

func (x *GetPayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutRequest.ProtoReflect.Descriptor instead.
func (*GetPayoutRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetPayoutRequest) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

type GetPayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutResponse) Reset() {
	*x = GetPayoutResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutResponse) ProtoMessage() {}

func (x *GetPayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutResponse.ProtoReflect.Descriptor instead.
func (*GetPayoutResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetPayoutResponse) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

func (x *GetPayoutResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPayoutResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPayoutResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPayoutResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type CancelPayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayoutId      string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPayoutRequest) Reset() {
	*x = CancelPayoutRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPayoutRequest) ProtoMessage() {}

func (x *CancelPayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPayoutRequest.ProtoReflect.Descriptor instead.
func (*CancelPayoutRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *CancelPayoutRequest) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

type CancelPayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPayoutResponse) Reset() {
	*x = CancelPayoutResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPayoutResponse) ProtoMessage() {}

func (x *CancelPayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPayoutResponse.ProtoReflect.Descriptor instead.
func (*CancelPayoutResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *CancelPayoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ApplyProviderUpdateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PayoutId          string                 `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	ProviderStatus    string                 `protobuf:"bytes,2,opt,name=provider_status,json=providerStatus,proto3" json:"provider_status,omitempty"`
	ProviderReference string                 `protobuf:"bytes,3,opt,name=provider_reference,json=providerReference,proto3" json:"provider_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplyProviderUpdateRequest) Reset() {
	*x = ApplyProviderUpdateRequest{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProviderUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProviderUpdateRequest) ProtoMessage() {}

func (x *ApplyProviderUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProviderUpdateRequest.ProtoReflect.Descriptor instead.
func (*ApplyProviderUpdateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyProviderUpdateRequest) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

func (x *ApplyProviderUpdateRequest) GetProviderStatus() string {
	if x != nil {
		return x.ProviderStatus
	}
	return ""
}

func (x *ApplyProviderUpdateRequest) GetProviderReference() string {
	if x != nil {
		return x.ProviderReference
	}
	return ""
}

type ApplyProviderUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyProviderUpdateResponse) Reset() {
	*x = ApplyProviderUpdateResponse{}
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProviderUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProviderUpdateResponse) ProtoMessage() {}

func (x *ApplyProviderUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProviderUpdateResponse.ProtoReflect.Descriptor instead.
func (*ApplyProviderUpdateResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyProviderUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_orchestrator_v1_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_v1_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\"orchestrator/v1/orchestrator.proto\x12\x0forchestrator.v1\"\x82\x01\n" +
	"\x13CreatePayoutRequest\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\"K\n" +
	"\x14CreatePayoutResponse\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"/\n" +
	"\x10GetPayoutRequest\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\"\x98\x01\n" +
	"\x11GetPayoutResponse\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\"2\n" +
	"\x13CancelPayoutRequest\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\"0\n" +
	"\x14CancelPayoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x91\x01\n" +
	"\x1aApplyProviderUpdateRequest\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\x12'\n" +
	"\x0fprovider_status\x18\x02 \x01(\tR\x0eproviderStatus\x12-\n" +
	"\x12provider_reference\x18\x03 \x01(\tR\x11providerReference\"7\n" +
	"\x1bApplyProviderUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8f\x03\n" +
	"\rPayoutService\x12[\n" +
	"\fCreatePayout\x12$.orchestrator.v1.CreatePayoutRequest\x1a%.orchestrator.v1.CreatePayoutResponse\x12R\n" +
	"\tGetPayout\x12!.orchestrator.v1.GetPayoutRequest\x1a\".orchestrator.v1.GetPayoutResponse\x12[\n" +
	"\fCancelPayout\x12$.orchestrator.v1.CancelPayoutRequest\x1a%.orchestrator.v1.CancelPayoutResponse\x12p\n" +
	"\x13ApplyProviderUpdate\x12+.orchestrator.v1.ApplyProviderUpdateRequest\x1a,.orchestrator.v1.ApplyProviderUpdateResponseBTZRgithub.com/bashkirian/fintech-project/libs/genproto/orchestrator/v1;orchestratorv1b\x06proto3"

var (
	file_orchestrator_v1_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_v1_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_v1_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_v1_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_v1_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_v1_orchestrator_proto_rawDesc), len(file_orchestrator_v1_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_v1_orchestrator_proto_rawDescData
}

var file_orchestrator_v1_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_orchestrator_v1_orchestrator_proto_goTypes = []any{
	(*CreatePayoutRequest)(nil),         // 0: orchestrator.v1.CreatePayoutRequest
	(*CreatePayoutResponse)(nil),        // 1: orchestrator.v1.CreatePayoutResponse
	(*GetPayoutRequest)(nil),            // 2: orchestrator.v1.GetPayoutRequest
	(*GetPayoutResponse)(nil),           // 3: orchestrator.v1.GetPayoutResponse
	(*CancelPayoutRequest)(nil),         // 4: orchestrator.v1.CancelPayoutRequest
	(*CancelPayoutResponse)(nil),        // 5: orchestrator.v1.CancelPayoutResponse
	(*ApplyProviderUpdateRequest)(nil),  // 6: orchestrator.v1.ApplyProviderUpdateRequest
	(*ApplyProviderUpdateResponse)(nil), // 7: orchestrator.v1.ApplyProviderUpdateResponse
}
var file_orchestrator_v1_orchestrator_proto_depIdxs = []int32{
	0, // 0: orchestrator.v1.PayoutService.CreatePayout:input_type -> orchestrator.v1.CreatePayoutRequest
	2, // 1: orchestrator.v1.PayoutService.GetPayout:input_type -> orchestrator.v1.GetPayoutRequest
	4, // 2: orchestrator.v1.PayoutService.CancelPayout:input_type -> orchestrator.v1.CancelPayoutRequest
	6, // 3: orchestrator.v1.PayoutService.ApplyProviderUpdate:input_type -> orchestrator.v1.ApplyProviderUpdateRequest
	1, // 4: orchestrator.v1.PayoutService.CreatePayout:output_type -> orchestrator.v1.CreatePayoutResponse
	3, // 5: orchestrator.v1.PayoutService.GetPayout:output_type -> orchestrator.v1.GetPayoutResponse
	5, // 6: orchestrator.v1.PayoutService.CancelPayout:output_type -> orchestrator.v1.CancelPayoutResponse
	7, // 7: orchestrator.v1.PayoutService.ApplyProviderUpdate:output_type -> orchestrator.v1.ApplyProviderUpdateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orchestrator_v1_orchestrator_proto_init() }
func file_orchestrator_v1_orchestrator_proto_init() {
	if File_orchestrator_v1_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_v1_orchestrator_proto_rawDesc), len(file_orchestrator_v1_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_v1_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_v1_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_v1_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_v1_orchestrator_proto = out.File
	file_orchestrator_v1_orchestrator_proto_goTypes = nil
	file_orchestrator_v1_orchestrator_proto_depIdxs = nil
}
