// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: orchestrator/v1/orchestrator.proto

package orchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayoutService_CreatePayout_FullMethodName        = "/orchestrator.v1.PayoutService/CreatePayout"
	PayoutService_GetPayout_FullMethodName           = "/orchestrator.v1.PayoutService/GetPayout"
	PayoutService_CancelPayout_FullMethodName        = "/orchestrator.v1.PayoutService/CancelPayout"
	PayoutService_ApplyProviderUpdate_FullMethodName = "/orchestrator.v1.PayoutService/ApplyProviderUpdate"
)

// PayoutServiceClient is the client API for PayoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayoutServiceClient interface {
	CreatePayout(ctx context.Context, in *CreatePayoutRequest, opts ...grpc.CallOption) (*CreatePayoutResponse, error)
	GetPayout(ctx context.Context, in *GetPayoutRequest, opts ...grpc.CallOption) (*GetPayoutResponse, error)
	CancelPayout(ctx context.Context, in *CancelPayoutRequest, opts ...grpc.CallOption) (*CancelPayoutResponse, error)
	// Stub: called by provider webhook to propagate status updates.
	ApplyProviderUpdate(ctx context.Context, in *ApplyProviderUpdateRequest, opts ...grpc.CallOption) (*ApplyProviderUpdateResponse, error)
}

type payoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPayoutServiceClient(cc grpc.ClientConnInterface) PayoutServiceClient {
	return &payoutServiceClient{cc}
}

func (c *payoutServiceClient) CreatePayout(ctx context.Context, in *CreatePayoutRequest, opts ...grpc.CallOption) (*CreatePayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePayoutResponse)
	err := c.cc.Invoke(ctx, PayoutService_CreatePayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutServiceClient) GetPayout(ctx context.Context, in *GetPayoutRequest, opts ...grpc.CallOption) (*GetPayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutResponse)
	err := c.cc.Invoke(ctx, PayoutService_GetPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutServiceClient) CancelPayout(ctx context.Context, in *CancelPayoutRequest, opts ...grpc.CallOption) (*CancelPayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPayoutResponse)
	err := c.cc.Invoke(ctx, PayoutService_CancelPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payoutServiceClient) ApplyProviderUpdate(ctx context.Context, in *ApplyProviderUpdateRequest, opts ...grpc.CallOption) (*ApplyProviderUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyProviderUpdateResponse)
	err := c.cc.Invoke(ctx, PayoutService_ApplyProviderUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayoutServiceServer is the server API for PayoutService service.
// All implementations must embed UnimplementedPayoutServiceServer
// for forward compatibility.
type PayoutServiceServer interface {
	CreatePayout(context.Context, *CreatePayoutRequest) (*CreatePayoutResponse, error)
	GetPayout(context.Context, *GetPayoutRequest) (*GetPayoutResponse, error)
	CancelPayout(context.Context, *CancelPayoutRequest) (*CancelPayoutResponse, error)
	// Stub: called by provider webhook to propagate status updates.
	ApplyProviderUpdate(context.Context, *ApplyProviderUpdateRequest) (*ApplyProviderUpdateResponse, error)
	mustEmbedUnimplementedPayoutServiceServer()
}

// UnimplementedPayoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayoutServiceServer struct{}

func (UnimplementedPayoutServiceServer) CreatePayout(context.Context, *CreatePayoutRequest) (*CreatePayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayout not implemented")
}
func (UnimplementedPayoutServiceServer) GetPayout(context.Context, *GetPayoutRequest) (*GetPayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayout not implemented")
}
func (UnimplementedPayoutServiceServer) CancelPayout(context.Context, *CancelPayoutRequest) (*CancelPayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPayout not implemented")
}
func (UnimplementedPayoutServiceServer) ApplyProviderUpdate(context.Context, *ApplyProviderUpdateRequest) (*ApplyProviderUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyProviderUpdate not implemented")
}
func (UnimplementedPayoutServiceServer) mustEmbedUnimplementedPayoutServiceServer() {}
func (UnimplementedPayoutServiceServer) testEmbeddedByValue()                       {}

// UnsafePayoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayoutServiceServer will
// result in compilation errors.
type UnsafePayoutServiceServer interface {
	mustEmbedUnimplementedPayoutServiceServer()
}

func RegisterPayoutServiceServer(s grpc.ServiceRegistrar, srv PayoutServiceServer) {
	// If the following call panics, it indicates UnimplementedPayoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayoutService_ServiceDesc, srv)
}

func _PayoutService_CreatePayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServiceServer).CreatePayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayoutService_CreatePayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServiceServer).CreatePayout(ctx, req.(*CreatePayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayoutService_GetPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServiceServer).GetPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayoutService_GetPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServiceServer).GetPayout(ctx, req.(*GetPayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayoutService_CancelPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServiceServer).CancelPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayoutService_CancelPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServiceServer).CancelPayout(ctx, req.(*CancelPayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayoutService_ApplyProviderUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyProviderUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayoutServiceServer).ApplyProviderUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayoutService_ApplyProviderUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayoutServiceServer).ApplyProviderUpdate(ctx, req.(*ApplyProviderUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayoutService_ServiceDesc is the grpc.ServiceDesc for PayoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.v1.PayoutService",
	HandlerType: (*PayoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayout",
			Handler:    _PayoutService_CreatePayout_Handler,
		},
		{
			MethodName: "GetPayout",
			Handler:    _PayoutService_GetPayout_Handler,
		},
		{
			MethodName: "CancelPayout",
			Handler:    _PayoutService_CancelPayout_Handler,
		},
		{
			MethodName: "ApplyProviderUpdate",
			Handler:    _PayoutService_ApplyProviderUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator/v1/orchestrator.proto",
}
